theme: jekyll-theme-minimal
title: XXX group's homepage
description: Welcome to my group website!
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
noscript: false
kramdown:
math_engine: mathjax
syntax_highlighter: rouge
